"""Added genre and moviegenre tables for normalization

Revision ID: 473a5c9bb2b4
Revises: 3cf2606c1637
Create Date: 2025-03-02 22:14:37.979552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473a5c9bb2b4'
down_revision: Union[str, None] = '3cf2606c1637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'genres', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_column('genres', 'name')
    # ### end Alembic commands ###
