"""adjusted review table more better review storage

Revision ID: 64b26b2dd31f
Revises: 7d38febc43cb
Create Date: 2025-03-03 09:49:14.325794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b26b2dd31f'
down_revision: Union[str, None] = '7d38febc43cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_text', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('source', sa.String(), nullable=True))
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_reviews_sentiment'), 'reviews', ['sentiment'], unique=False)
    op.drop_constraint('reviews_movie_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'movies', ['movie_id'], ['movie_id'], ondelete='CASCADE')
    op.drop_column('reviews', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key('reviews_movie_id_fkey', 'reviews', 'movies', ['movie_id'], ['movie_id'])
    op.drop_index(op.f('ix_reviews_sentiment'), table_name='reviews')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'source')
    op.drop_column('reviews', 'review_text')
    # ### end Alembic commands ###
