"""adjusted watch history table

Revision ID: 7eb51726c549
Revises: ad0f67186f3e
Create Date: 2025-06-11 20:38:53.251790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb51726c549'
down_revision: Union[str, None] = 'ad0f67186f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_watch_user', 'watch_history', ['user_id'], unique=False)
    op.create_unique_constraint('uix_user_movie', 'watch_history', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_movie', 'watch_history', type_='unique')
    op.drop_index('ix_watch_user', table_name='watch_history')
    # ### end Alembic commands ###
