"""added default of 0 to vote avg and count

Revision ID: 9e725c0916d9
Revises: d6e92fd01187
Create Date: 2025-03-03 13:10:47.894067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e725c0916d9'
down_revision: Union[str, None] = 'd6e92fd01187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'vote_average',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('movies', 'vote_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'vote_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'vote_average',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
