"""added tmdb_id for API lookup

Revision ID: ad0f67186f3e
Revises: 4cdcaa65b6c3
Create Date: 2025-03-25 11:25:18.771970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0f67186f3e'
down_revision: Union[str, None] = '4cdcaa65b6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'movies', ['tmdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'tmdb_id')
    # ### end Alembic commands ###
