"""added index to genre tbale

Revision ID: d6e92fd01187
Revises: e67c9aa45333
Create Date: 2025-03-03 12:18:18.729770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e92fd01187'
down_revision: Union[str, None] = 'e67c9aa45333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('genres_name_key', 'genres', type_='unique')
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.create_unique_constraint('genres_name_key', 'genres', ['name'])
    # ### end Alembic commands ###
