"""added vote_avg,vote_count,runtime and DateTime to Date

Revision ID: e67c9aa45333
Revises: 64b26b2dd31f
Create Date: 2025-03-03 12:13:14.685364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e67c9aa45333'
down_revision: Union[str, None] = '64b26b2dd31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('vote_average', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('runtime', sa.Integer(), nullable=True))
    op.alter_column('movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('movies', 'runtime')
    op.drop_column('movies', 'vote_count')
    op.drop_column('movies', 'vote_average')
    # ### end Alembic commands ###
